-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 18:25:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_products
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_products` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `database_products` ;

-- -----------------------------------------------------
-- Table `database_products`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_products`.`categoria` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `database_products`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_products`.`estado` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `database_products`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_products`.`products` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(255) NOT NULL DEFAULT '',
  `descripcionProducto` VARCHAR(500) NOT NULL DEFAULT '',
  `nombreArchivo` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IdEstado` INT(11) NOT NULL,
  `IdCategoria` INT(11) NOT NULL,
  PRIMARY KEY (`Id`, `IdEstado`, `IdCategoria`),
  INDEX `fk_products_estado_idx` (`IdEstado` ASC) VISIBLE,
  INDEX `fk_products_categoria1_idx` (`IdCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_products_estado`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `database_products`.`estado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categoria1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `database_products`.`categoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
